gem_version: 0.2.15
encoding: UTF-8
title: Arquillian
tagline: Write Real Tests
description: An innovative testing platform for the Java Virtual Machine (JVM). Open source. Highly extensible.
definition: "Arquillian is open source software that empowers you to test JVM-based applications more effectively. Created to defend the software galaxy from bugs, Arquillian brings your test to the runtime so you can focus on testing your application's behavior rather than managing the runtime. Using Arquillian, you can develop a comprehensive suite of tests from the convenience of your IDE and run them in any IDE, build tool or continuous integration environment."
# author is used in the atom feed
author: Arquillian Project
#keywords: arquillian,drone,graphene,testing,junit,testng,selenium,javaee,jboss,redhat,openshift,open source
jira_key: ARQ
ohloh_id: 480465
# use repos_dir to move clones outside of website tree
repos_dir: /tmp/arqrepos
resolve_published_artifacts: false
github_organization: arquillian
source_repo: https://github.com/arquillian
website_source:
  repo: https://github.com/arquillian/arquillian.github.com
  branch: develop
speakers_team_id: 146647
issue_tracker: https://issues.jboss.org/browse/ARQ
api_spi_docs: http://docs.jboss.org/arquillian/aggregate/latest
ref_guide: https://docs.jboss.org/author/display/ARQ/Reference+Guide
project_space: http://community.jboss.org/en/arquillian
faqs: http://community.jboss.org/en/arquillian/faq
migration_guides: http://community.jboss.org/wiki/ArquillianMigrationGuides
user_forum: http://community.jboss.org/en/arquillian?view=discussions
dev_forum: http://community.jboss.org/en/arquillian/dev?view=discussions
irc_channel: arquillian
irc_transcripts: http://transcripts.jboss.org/channel/irc.freenode.org/%23arquillian/
jboss_org_node_path: /arquillian_test
licenses:
  "Apache-2.0": "ASL v2.0"
  "LGPL-2.1": "LGPL v2.1"
team: [aslakknutsen, mojavelinux, graphitefriction, alrubinger, kpiwko, lfryc, bartoszmajsak, pmuir]
haml:
  attr_wrapper: '"'
  escape_attrs: :once
textile: ['no_span_caps']
disqus_generate_id: true
google_plusone: false
profiles:
  debug:
    show_debug: true
  development:
  sandbox:
    base_url: http://sandbox.arquillian.org:4242
    disqus: arquillian-sandbox
    disqus_developer: true
  staging:
    base_url: http://staging-arquillian.rhcloud.com
    google_analytics: UA-18727998-4
    disqus: arquillian-staging
    resolve_published_artifacts: true
  production:
    base_url: http://arquillian.org
    google_analytics: UA-18727998-3
    disqus: arquillian
    resolve_published_artifacts: true
    fingerprint_assets: true
    google_plusone: true
    minify: true
    jboss_org_node_path: /arquillian
    deploy:
      host: github_pages
      branch: master
